name: Coconut.NetCore.RabbitMQ.Core
env: 
  APPLICATION_NAME: "Coconut.NetCore.RabbitMQ.Core"
  VERSION_BY_TAG: "${{ github.ref_name }}"

on:
  create:
    tags:
      - v*.*.*

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2
      - name: Setup .NET Core
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: 5.0.102
        
      - name: Install dependencies
        run: dotnet restore ${{ env.APPLICATION_NAME }}.sln
        
      - name: Change Version
        run: sed -i -e 's/0.0.0.0/${{ env.VERSION_BY_TAG }}/g' src/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.csproj

      - name: Build
        run: dotnet build ${{ env.APPLICATION_NAME }}.sln --configuration Release
      
      - name: Tests
        run: dotnet test tests/${{ env.APPLICATION_NAME }}.Tests/${{ env.APPLICATION_NAME }}.Tests.csproj

      - name: Publish ${{ env.APPLICATION_NAME }}
        uses: rohith/publish-nuget@v2
        with:
          PROJECT_FILE_PATH: src/${{ env.APPLICATION_NAME }}/${{ env.APPLICATION_NAME }}.csproj
          VERSION_STATIC: ${{ env.VERSION_BY_TAG }}
          NUGET_KEY: ${{secrets.NUGET_API_KEY}}
          