name: Coconut.NetCore.RabbitMQ
env: 
  APPLICATION_NAME: "Coconut.NetCore.RabbitMQ"
  GITHUB_REF: "${{ github.ref }}"
  GITHUB_REF_NAME: "${{ github.ref_name }}"

on:
  create:
    tags:
      - v*.*.*

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run:
          echo GITHUB_REF is ${{env.GITHUB_REF}}
          echo APPLICATION_NAME is ${{env.APPLICATION_NAME}}
          echo GITHUB_REF_NAME is ${{env.GITHUB_REF_NAME}}
        