name: Coconut.NetCore.RabbitMQ
env: 
  APPLICATION_NAME: "Coconut.NetCore.RabbitMQ"

on:
  create:
    tags:
      - v*.*.*

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: echo versions
        run: 
          echo "GITHUB_REF - ${{ GITHUB_REF }}"
          echo "GITHUB_REF_NAME - ${{ GITHUB_REF_NAME }}"
  
  