name: Coconut.NetCore.RabbitMQ
env: 
  APPLICATION_NAME: "Coconut.NetCore.RabbitMQ"

on:
  create:
    tags:
      - v*.*.*

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: 
          echo ::set-output name=VERSION::$(echo $GITHUB_REF | cut -d / -f 3)
          echo Tag version ${{ steps.get_version.outputs.VERSION }}
  
  