name: Coconut.NetCore.RabbitMQ
env: 
  APPLICATION_NAME: "Coconut.NetCore.RabbitMQ"
  VERSION_NAME: "{{ $GITHUB_REF | cut -d / -f }}"

on:
  create:
    tags:
      - v*.*.*

jobs:
  echo-version:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: 
          ::set-output name=VERSION::$(echo $env.VERSION_NAME)
          echo Tag version ${{ steps.get_version.outputs.VERSION }}
        